const trophies = [
  {
    id: "trophy_1",
    name: "The Shadow Mark",
    howToGet: "Receive The Mark of the RNG",
    points: -10,
    secret: false,
    image: "placeholder.jpg",
    owned: false,
  },
  {
    id: "trophy_2",
    name: "Completionist I",
    howToGet: "Have 10+ 1-Point Trophies on the Trophy Page",
    points: 1,
    secret: false,
    image: "placeholder.jpg",
    owned: false,
  },
  {
    id: "trophy_3",
    name: "Adelheid",
    howToGet: "Get a Yakuman in Mahjong without cheating",
    points: 1,
    secret: true,
    image: "placeholder.jpg",
    owned: false,
  },
  {
    id: "trophy_4",
    name: "A-gah-gah-gah",
    howToGet: "Recover from negative HP via Veggies",
    points: 1,
    secret: true,
    image: "placeholder.jpg",
    owned: false,
  },
  {
    id: "trophy_5",
    name: "Alone at Last",
    howToGet: "Take 1 Ally into the Tunnel",
    points: 1,
    secret: true,
    image: "placeholder.jpg",
    owned: false,
  },
  {
    id: "trophy_6",
    name: "Big Fudge",
    howToGet: "Get the Max Score in a Tsukiball game",
    points: 1,
    secret: true,
    image: "placeholder.jpg",
    owned: false,
  },
  {
    id: "trophy_7",
    name: "Bluff Boss",
    howToGet: "Showdown with High Card and have the opponent fold",
    points: 1,
    secret: true,
    image: "placeholder.jpg",
    owned: false,
  },
  {
    id: "trophy_8",
    name: "Board Breaker",
    howToGet: "Get a Triple Bullseye with a regular Kunai",
    points: 1,
    secret: true,
    image: "placeholder.jpg",
    owned: false,
  },
  {
    id: "trophy_9",
    name: "Both Shoulders",
    howToGet: "Spin the wheel with both Billy and The Rack",
    points: 1,
    secret: true,
    image: "placeholder.jpg",
    owned: false,
  },
  {
    id: "trophy_10",
    name: "Buggin",
    howToGet: "Hang out with Bugman Lvl. 2 via MPB",
    points: 1,
    secret: true,
    image: "placeholder.jpg",
    owned: false,
  },
  {
    id: "trophy_11",
    name: "Call it a Comeback",
    howToGet: "Defeat a Titan with 10 or less HP remaining",
    points: 1,
    secret: true,
    image: "placeholder.jpg",
    owned: false,
  },
  {
    id: "trophy_12",
    name: "Checking It Twice",
    howToGet: "Visit the Trophy Room with both Maximum Naughtinessand Niceness awards at once",
    points: 1,
    secret: true,
    image: "placeholder.jpg",
    owned: false,
  },
  {
    id: "trophy_13",
    name: "Clipper",
    howToGet: "Use a Daily Fail coupon to buy 1 Kunai and get 1 free",
    points: 1,
    secret: true,
    image: "placeholder.jpg",
    owned: false,
  },
  {
    id: "trophy_14",
    name: "Completionist II",
    howToGet: "Have 20+ 1-Point Trophies on the Trophy Page",
    points: 1,
    secret: true,
    image: "placeholder.jpg",
    owned: false,
  },
  {
    id: "trophy_15",
    name: "Completionist III",
    howToGet: "Have 30+ 1-Point Trophies on the Trophy Page",
    points: 1,
    secret: true,
    image: "placeholder.jpg",
    owned: false,
  },
  {
    id: "trophy_16",
    name: "Completionist 11",
    howToGet: "Have 50+ 1-Point Trophies on the Trophy Page",
    points: 1,
    secret: true,
    image: "placeholder.jpg",
    owned: false,
  },
  {
    id: "trophy_17",
    name: "Conssssolation",
    howToGet: "Take the deal with SNAKEMAN in your bucket",
    points: 1,
    secret: true,
    image: "placeholder.jpg",
    owned: false,
  },
  {
    id: "trophy_18",
    name: "Consolation Prize",
    howToGet: "Win 500,000 Ryo in a game of SNAKEMAN or No SNAKEMAN",
    points: 1,
    secret: true,
    image: "placeholder.jpg",
    owned: false,
  },
  {
    id: "trophy_19",
    name: "Counting Carbs",
    howToGet: "Drink Diet Soda with 0 Greass",
    points: 1,
    secret: true,
    image: "placeholder.jpg",
    owned: false,
  },
  {
    id: "trophy_20",
    name: "Dark Victor",
    howToGet: "Win an Arena Fight during the Dark Hour",
    points: 1,
    secret: true,
    image: "placeholder.jpg",
    owned: false,
  },
  {
    id: "trophy_21",
    name: "Dead Man Walking",
    howToGet: "Defeat 100 zombjas in one map without an equipped weapon",
    points: 1,
    secret: true,
    image: "placeholder.jpg",
    owned: false,
  },
  {
    id: "trophy_22",
    name: "Dressed to Kill",
    howToGet: "Start a Con with 11 Complete Cosplay Costumes",
    points: 1,
    secret: true,
    image: "placeholder.jpg",
    owned: false,
  },
  {
    id: "trophy_23",
    name: "Einhorn is Finkle",
    howToGet: "Get 11 Pets",
    points: 1,
    secret: true,
    image: "placeholder.jpg",
    owned: false,
  },
  {
    id: "trophy_24",
    name: "Enough Already",
    howToGet: "Achieve the maximum Season (Season 111)",
    points: 1,
    secret: true,
    image: "placeholder.jpg",
    owned: false,
  },
  {
    id: "trophy_25",
    name: "Everybody Out",
    howToGet: "Checkout 6+ customers at once",
    points: 1,
    secret: true,
    image: "placeholder.jpg",
    owned: false,
  },
  {
    id: "trophy_26",
    name: "Fired on Friday",
    howToGet: "Rage out with 1 Time remaining",
    points: 1,
    secret: true,
    image: "placeholder.jpg",
    owned: false,
  },
  {
    id: "trophy_27",
    name: "First?",
    howToGet: "Get First place in First Loser",
    points: 1,
    secret: true,
    image: "placeholder.jpg",
    owned: false,
  },
  {
    id: "trophy_28",
    name: "Flushed",
    howToGet: "Discard an entire Royal Flush at once",
    points: 1,
    secret: true,
    image: "placeholder.jpg",
    owned: false,
  },
  {
    id: "trophy_29",
    name: "Forever Alone",
    howToGet: "Go in the Tunnel alone",
    points: 1,
    secret: true,
    image: "placeholder.jpg",
    owned: false,
  },
  {
    id: "trophy_30",
    name: "Four Day Weekend",
    howToGet: "Vacation Thursday, Friday, Saturday, and Sunday",
    points: 1,
    secret: true,
    image: "placeholder.jpg",
    owned: false,
  },
  {
    id: "trophy_31",
    name: "Four Seasons",
    howToGet: "Get 50+ points in one Flower Wars hand",
    points: 1,
    secret: true,
    image: "placeholder.jpg",
    owned: false,
  },
  {
    id: "trophy_32",
    name: "Gone",
    howToGet: "Finish a Crazy Hard ride within 60 seconds",
    points: 1,
    secret: true,
    image: "placeholder.jpg",
    owned: false,
  },
  {
    id: "trophy_33",
    name: "Handoff",
    howToGet: "Have A A Ron check out your last customer",
    points: 1,
    secret: true,
    image: "placeholder.jpg",
    owned: false,
  },
  {
    id: "trophy_34",
    name: "Hard Worker",
    howToGet: "Do 11 S-Rank Missions in one day",
    points: 1,
    secret: true,
    image: "placeholder.jpg",
    owned: false,
  },
  {
    id: "trophy_35",
    name: "Hero's Reward",
    howToGet: "Turn in 1 S-Rank Emblem successfully",
    points: 1,
    secret: true,
    image: "placeholder.jpg",
    owned: false,
  },
  {
    id: "trophy_36",
    name: "High Summoner",
    howToGet: "Summon 11 summons in a day",
    points: 1,
    secret: true,
    image: "placeholder.jpg",
    owned: false,
  },
  {
    id: "trophy_37",
    name: "I Miss You Already",
    howToGet: "Change your Team to the same Team you just had",
    points: 1,
    secret: true,
    image: "placeholder.jpg",
    owned: false,
  },
  {
    id: "trophy_38",
    name: "Indecisive Reaper",
    howToGet: "Change to all four Reaper States in one day",
    points: 1,
    secret: true,
    image: "placeholder.jpg",
    owned: false,
  },
  {
    id: "trophy_39",
    name: "Independent Contractor",
    howToGet: "Sell a Village Contract",
    points: 1,
    secret: true,
    image: "placeholder.jpg",
    owned: false,
  },
  {
    id: "trophy_40",
    name: "In Phase",
    howToGet: "Defeat 2 Phases in one day",
    points: 1,
    secret: true,
    image: "placeholder.jpg",
    owned: false,
  },
  {
    id: "trophy_41",
    name: "Just a Piece",
    howToGet: "Sharing Delicious Cake with the village",
    points: 1,
    secret: true,
    image: "placeholder.jpg",
    owned: false,
  },
  {
    id: "trophy_42",
    name: "Killed to Dress",
    howToGet: "Start a Con with 111 Complete Cosplay Costumes",
    points: 1,
    secret: true,
    image: "placeholder.jpg",
    owned: false,
  },
  {
    id: "trophy_43",
    name: "KTHXBAIman",
    howToGet: "Bust out a Mahjong opponent with a Baiman",
    points: 1,
    secret: true,
    image: "placeholder.jpg",
    owned: false,
  },
  {
    id: "trophy_44",
    name: "Legen..dary",
    howToGet: "+111+ Successes on a Crank 11 S-Rank Mission",
    points: 1,
    secret: true,
    image: "placeholder.jpg",
    owned: false,
  },
  {
    id: "trophy_45",
    name: "Long Day Ahead",
    howToGet: "Achieve over 11,000 Stamina from consumables",
    points: 1,
    secret: true,
    image: "placeholder.jpg",
    owned: false,
  },
  {
    id: "trophy_46",
    name: "Low Roller",
    howToGet: "Get 6+ Pachinko Comps in one turn-in",
    points: 1,
    secret: true,
    image: "placeholder.jpg",
    owned: false,
  },
  {
    id: "trophy_47",
    name: "Lucre Libre",
    howToGet: "Throw a Lucha Fight",
    points: 1,
    secret: true,
    image: "placeholder.jpg",
    owned: false,
  },
  {
    id: "trophy_48",
    name: "Many Hands",
    howToGet: "Load the truck without injury",
    points: 1,
    secret: true,
    image: "placeholder.jpg",
    owned: false,
  },
  {
    id: "trophy_49",
    name: "Meddling Kids",
    howToGet: "Beat an S-Rank Mission with Lvl 3. Billy, Pinky, and Stalkergirl",
    points: 1,
    secret: true,
    image: "placeholder.jpg",
    owned: false,
  },
  {
    id: "trophy_50",
    name: "Mercenary",
    howToGet: "Turn in 111+ contracts at once",
    points: 1,
    secret: true,
    image: "placeholder.jpg",
    owned: false,
  },
  {
    id: "trophy_51",
    name: "Movin' On Up",
    howToGet: "45+ Lvl. 2 or greater Allies on the Team Page",
    points: 1,
    secret: true,
    image: "placeholder.jpg",
    owned: false,
  },
  {
    id: "trophy_52",
    name: "One Man Army",
    howToGet: "Win 111 arena matches in a day",
    points: 1,
    secret: true,
    image: "placeholder.jpg",
    owned: false,
  },
  {
    id: "trophy_53",
    name: "Palate Cleanser",
    howToGet: "Drink 12 or more different Juice Types at once",
    points: 1,
    secret: true,
    image: "placeholder.jpg",
    owned: false,
  },
  {
    id: "trophy_54",
    name: "Popular",
    howToGet: "Visit your Team Page while hanging out with 11+ Allies",
    points: 1,
    secret: true,
    image: "placeholder.jpg",
    owned: false,
  },
  {
    id: "trophy_55",
    name: "Psychological Issues",
    howToGet: "Trapdoor your future self",
    points: 1,
    secret: true,
    image: "placeholder.jpg",
    owned: false,
  },
  {
    id: "trophy_56",
    name: "Rave Grandmaster",
    howToGet: "Get 11,000+ in the Rave",
    points: 1,
    secret: true,
    image: "placeholder.jpg",
    owned: false,
  },
  {
    id: "trophy_57",
    name: "Sacred Hang",
    howToGet: "Visit your special Field",
    points: 1,
    secret: true,
    image: "placeholder.jpg",
    owned: false,
  },
  {
    id: "trophy_58",
    name: "Self Five",
    howToGet: "Attempt to Walk Together with yourself",
    points: 1,
    secret: true,
    image: "placeholder.jpg",
    owned: false,
  },
  {
    id: "trophy_59",
    name: "Showoff",
    howToGet: "Visit the Party House with over 11,000,000 Ranking XP",
    points: 1,
    secret: true,
    image: "placeholder.jpg",
    owned: false,
  },
  {
    id: "trophy_60",
    name: "Stupid Devil Machines",
    howToGet: "Kick the Crane Machine with your last 2 Stamina",
    points: 1,
    secret: true,
    image: "placeholder.jpg",
    owned: false,
  },
  {
    id: "trophy_61",
    name: "Super Failure",
    howToGet: "SuperFail on Attempt 2",
    points: 1,
    secret: true,
    image: "placeholder.jpg",
    owned: false,
  },
  {
    id: "trophy_62",
    name: "Surefire Strategy",
    howToGet: "Have a bet on all possible spins in Roulette",
    points: 1,
    secret: true,
    image: "placeholder.jpg",
    owned: false,
  },
  {
    id: "trophy_63",
    name: "That Was Easy",
    howToGet: "Say 'Trophy' in Hidden Forbidden Holy Ground",
    points: 1,
    secret: true,
    image: "placeholder.jpg",
    owned: false,
  },
  {
    id: "trophy_64",
    name: "The Most Dangerous Strut",
    howToGet: "Escape the Squee during a four hour hunt",
    points: 1,
    secret: true,
    image: "placeholder.jpg",
    owned: false,
  },
  {
    id: "trophy_65",
    name: "The Pizza Is Not Enough",
    howToGet: "Successfully create an Ultimate Pizza",
    points: 1,
    secret: true,
    image: "placeholder.jpg",
    owned: false,
  },
  {
    id: "trophy_66",
    name: "Tsk-Ts...Oh.",
    howToGet: "Have a Clean store when a Tsk goes to Tsk in Retail",
    points: 1,
    secret: true,
    image: "placeholder.jpg",
    owned: false,
  },
  {
    id: "trophy_67",
    name: "Two Weeks Notice",
    howToGet: "Vacation with 14+ days",
    points: 1,
    secret: true,
    image: "placeholder.jpg",
    owned: false,
  },
  {
    id: "trophy_68",
    name: "Universal Acclaim",
    howToGet: "Have 99+ Allies on the Team page",
    points: 1,
    secret: true,
    image: "placeholder.jpg",
    owned: false,
  },
  {
    id: "trophy_69",
    name: "Value Meal",
    howToGet: "Eat 4 different Greassy Items in a row",
    points: 1,
    secret: true,
    image: "placeholder.jpg",
    owned: false,
  },
  {
    id: "trophy_70",
    name: "Vwom",
    howToGet: "Attack with an 11Saber",
    points: 1,
    secret: true,
    image: "placeholder.jpg",
    owned: false,
  },
  {
    id: "trophy_71",
    name: "Work Angry",
    howToGet: "Clear all customers with +200 Rage",
    points: 1,
    secret: true,
    image: "placeholder.jpg",
    owned: false,
  },
  {
    id: "trophy_72",
    name: "S-1",
    howToGet: "Get the Season One Collection",
    points: 5,
    secret: true,
    image: "placeholder.jpg",
    owned: false,
  },
  {
    id: "trophy_73",
    name: "S-2",
    howToGet: "Get the Season Two Collection",
    points: 5,
    secret: true,
    image: "placeholder.jpg",
    owned: false,
  },
  {
    id: "trophy_74",
    name: "S-3",
    howToGet: "Get the Season Three Collection",
    points: 5,
    secret: true,
    image: "placeholder.jpg",
    owned: false,
  },
  {
    id: "trophy_75",
    name: "S-4",
    howToGet: "Get the Season Four Collection",
    points: 5,
    secret: true,
    image: "placeholder.jpg",
    owned: false,
  },
  {
    id: "trophy_76",
    name: "S-5",
    howToGet: "Get the Season Five Collection",
    points: 5,
    secret: true,
    image: "placeholder.jpg",
    owned: false,
  },
  {
    id: "trophy_77",
    name: "Helpercats One",
    howToGet: "Get the first row of HelperCats",
    points: 5,
    secret: true,
    image: "placeholder.jpg",
    owned: false,
  },
  {
    id: "trophy_78",
    name: "Helpercats Two",
    howToGet: "Get the second row of HelperCats",
    points: 5,
    secret: true,
    image: "placeholder.jpg",
    owned: false,
  },
  {
    id: "trophy_79",
    name: "Aim For The Top",
    howToGet: "Bingo 5 Leaders in one day",
    points: 5,
    secret: false,
    image: "placeholder.jpg",
    owned: false,
  },
  {
    id: "trophy_80",
    name: "Big Three",
    howToGet: "Become Sannin",
    points: 5,
    secret: false,
    image: "placeholder.jpg",
    owned: false,
  },
  {
    id: "trophy_81",
    name: "Busted",
    howToGet: "Win in Mahjong with at least one other player in the negatives without cheating",
    points: 5,
    secret: false,
    image: "placeholder.jpg",
    owned: false,
  },
  {
    id: "trophy_82",
    name: "Bottoms Up",
    howToGet: "Get the Drunken Fist Theme",
    points: 5,
    secret: false,
    image: "placeholder.jpg",
    owned: false,
  },
  {
    id: "trophy_83",
    name: "Cosplay Complete",
    howToGet: "Wear all three parts of a single character's Cosplay",
    points: 5,
    secret: false,
    image: "placeholder.jpg",
    owned: false,
  },
  {
    id: "trophy_84",
    name: "Friday Knight",
    howToGet: "Won an FKF Qualifier FIGHTO Tournament",
    points: 5,
    secret: false,
    image: "placeholder.jpg",
    owned: false,
  },
  {
    id: "trophy_85",
    name: "Goth Goth Loli Loli",
    howToGet: "Get The Road to Womanhood Theme",
    points: 5,
    secret: false,
    image: "placeholder.jpg",
    owned: false,
  },
  {
    id: "trophy_86",
    name: "Head of the Class",
    howToGet: "Receive a score of 10 on the Chunin Exam",
    points: 5,
    secret: false,
    image: "placeholder.jpg",
    owned: false,
  },
  {
    id: "trophy_87",
    name: "Holy Ground",
    howToGet: "Visit Hidden-Forbidden-Holy Ground",
    points: 5,
    secret: false,
    image: "placeholder.jpg",
    owned: false,
  },
  {
    id: "trophy_88",
    name: "Into The Loop",
    howToGet: "Complete Season 1",
    points: 5,
    secret: false,
    image: "placeholder.jpg",
    owned: false,
  },
  {
    id: "trophy_89",
    name: "King Of The Monsters",
    howToGet: "+1000 Minion defeats as Kaiju",
    points: 5,
    secret: false,
    image: "placeholder.jpg",
    owned: false,
  },
  {
    id: "trophy_90",
    name: "Knightmare",
    howToGet: "Obtain the Knightmare Frame",
    points: 5,
    secret: false,
    image: "placeholder.jpg",
    owned: false,
  },
  {
    id: "trophy_91",
    name: "Loop The Loop",
    howToGet: "Complete Season 2",
    points: 5,
    secret: false,
    image: "placeholder.jpg",
    owned: false,
  },
  {
    id: "trophy_92",
    name: "Marked",
    howToGet: "Receive The Mark of Eleventy Billion",
    points: 5,
    secret: false,
    image: "placeholder.jpg",
    owned: false,
  },
  {
    id: "trophy_93",
    name: "Monster Hunter",
    howToGet: "Loop after winning a Monster Drop from a Defeated Kaiju",
    points: 5,
    secret: false,
    image: "placeholder.jpg",
    owned: false,
  },
  {
    id: "trophy_94",
    name: "Ninja World Warrior",
    howToGet: "Obtain the Letter of Marque",
    points: 5,
    secret: false,
    image: "placeholder.jpg",
    owned: false,
  },
  {
    id: "trophy_95",
    name: "No Sleep 'Til",
    howToGet: "Obtain 'Up All Night' Effect twice in a single BillyCon",
    points: 5,
    secret: false,
    image: "placeholder.jpg",
    owned: false,
  },
  {
    id: "trophy_96",
    name: "One in a Thousand",
    howToGet: "+1000 Minion defeats as Ninja",
    points: 5,
    secret: false,
    image: "placeholder.jpg",
    owned: false,
  },
  {
    id: "trophy_97",
    name: "Trophy Trophy",
    howToGet: "Got a Trophy for Loading the Truck (how meta)",
    points: 5,
    secret: false,
    image: "placeholder.jpg",
    owned: false,
  },
  {
    id: "trophy_98",
    name: "True Blood",
    howToGet: "Get True Blood of the Reaper",
    points: 5,
    secret: false,
    image: "placeholder.jpg",
    owned: false,
  },
  {
    id: "trophy_99",
    name: "Wheel Winner",
    howToGet: "Loop with the Necklace of the First HoCage, Stealth Suit, Codec, K-Dog's Headband, and Love Love Paradise",
    points: 5,
    secret: false,
    image: "placeholder.jpg",
    owned: false,
  },
  {
    id: "trophy_100",
    name: "Wotastic",
    howToGet: "Autowin a Mission Lady Scuffle",
    points: 5,
    secret: false,
    image: "placeholder.jpg",
    owned: false,
  },
  {
    id: "trophy_101",
    name: "Acedia",
    howToGet: "Complete RG Day One",
    points: 10,
    secret: true,
    image: "placeholder.jpg",
    owned: false,
  },
  {
    id: "trophy_102",
    name: "Baton Pass",
    howToGet: "Get the Red Skull Pin",
    points: 10,
    secret: true,
    image: "placeholder.jpg",
    owned: false,
  },
  {
    id: "trophy_103",
    name: "Brothers in Arms",
    howToGet: "Beat Difficulty 11 in Infinite Retail",
    points: 10,
    secret: true,
    image: "placeholder.jpg",
    owned: false,
  },
  {
    id: "trophy_104",
    name: "EGOT",
    howToGet: "Win all roles in BillyTV once",
    points: 10,
    secret: true,
    image: "placeholder.jpg",
    owned: false,
  },
  {
    id: "trophy_105",
    name: "Employee of the Week",
    howToGet: "Get a top 3 of the week wage performance in a Black Friday shift",
    points: 10,
    secret: true,
    image: "placeholder.jpg",
    owned: false,
  },
  {
    id: "trophy_106",
    name: "Fruit Dealer",
    howToGet: "Eat Fresh Fruit with 50+ Cool",
    points: 10,
    secret: true,
    image: "placeholder.jpg",
    owned: false,
  },
  {
    id: "trophy_107",
    name: "Fully Cranked",
    howToGet: "Defeat a Mission at Maximum Crank",
    points: 10,
    secret: true,
    image: "placeholder.jpg",
    owned: false,
  },
  {
    id: "trophy_108",
    name: "Gallery I",
    howToGet: "Complete the first Snooty Gallery Artwork",
    points: 10,
    secret: true,
    image: "placeholder.jpg",
    owned: false,
  },
  {
    id: "trophy_109",
    name: "Gift Giver",
    howToGet: "Put an Over 11000 or a Sho Nuff Elixir into the Hidden HoClaus gift pile",
    points: 10,
    secret: true,
    image: "placeholder.jpg",
    owned: false,
  },
  {
    id: "trophy_110",
    name: "Huzzah",
    howToGet: "Save Mimi",
    points: 10,
    secret: true,
    image: "placeholder.jpg",
    owned: false,
  },
  {
    id: "trophy_111",
    name: "In Kaiju It Means Love",
    howToGet: "Have 11 different tattoo touchup additions at once",
    points: 10,
    secret: true,
    image: "placeholder.jpg",
    owned: false,
  },
  {
    id: "trophy_112",
    name: "Land a Whale",
    howToGet: "Get the Whale to checkout in Retail",
    points: 10,
    secret: true,
    image: "placeholder.jpg",
    owned: false,
  },
  {
    id: "trophy_113",
    name: "Quantum Loop",
    howToGet: "Complete Captain's Log",
    points: 10,
    secret: true,
    image: "placeholder.jpg",
    owned: false,
  },
  {
    id: "trophy_114",
    name: "Smile for the Camera",
    howToGet: "Get 11 treats, a mask and a party invite in Candyween",
    points: 10,
    secret: true,
    image: "placeholder.jpg",
    owned: false,
  },
  {
    id: "trophy_115",
    name: "Spirit of Ninja-Mas",
    howToGet: "Complete Life Finds A Way",
    points: 10,
    secret: true,
    image: "placeholder.jpg",
    owned: false,
  },
  {
    id: "trophy_116",
    name: "The Unthinkable",
    howToGet: "Eat Ninja Cat Barf",
    points: 10,
    secret: true,
    image: "placeholder.jpg",
    owned: false,
  },
  {
    id: "trophy_117",
    name: "WotAdventure EX",
    howToGet: "Defeat a WotAdventure with Difficulty 1 or greater",
    points: 10,
    secret: true,
    image: "placeholder.jpg",
    owned: false,
  },
  {
    id: "trophy_118",
    name: "Aces High",
    howToGet: "Defeated King Omaha",
    points: 10,
    secret: false,
    image: "placeholder.jpg",
    owned: false,
  },
  {
    id: "trophy_119",
    name: "Avid Reader",
    howToGet: "Get an Item from Proof Reader in a Quest",
    points: 10,
    secret: false,
    image: "placeholder.jpg",
    owned: false,
  },
  {
    id: "trophy_120",
    name: "Biggest Fan",
    howToGet: "Have all BillyTV Autographs at 100% or more",
    points: 10,
    secret: false,
    image: "placeholder.jpg",
    owned: false,
  },
  {
    id: "trophy_121",
    name: "But Wait There's More",
    howToGet: "Made it successfully into (and out of) the BillyMaze",
    points: 10,
    secret: false,
    image: "placeholder.jpg",
    owned: false,
  },
  {
    id: "trophy_122",
    name: "Characolle Set One",
    howToGet: "Collect the first set of Truckload Trading Figures",
    points: 10,
    secret: false,
    image: "placeholder.jpg",
    owned: false,
  },
  {
    id: "trophy_123",
    name: "Characolle Set Two",
    howToGet: "Collect the second set of Truckload Trading Figures",
    points: 10,
    secret: false,
    image: "placeholder.jpg",
    owned: false,
  },
  {
    id: "trophy_124",
    name: "Chillin' With 11",
    howToGet: "Loop with Level 50 or greater in Tsukiball",
    points: 10,
    secret: false,
    image: "placeholder.jpg",
    owned: false,
  },
  {
    id: "trophy_125",
    name: "Dai Sei Kou!",
    howToGet: "Summon and Defeat a WorldKaiju",
    points: 10,
    secret: false,
    image: "placeholder.jpg",
    owned: false,
  },
  {
    id: "trophy_126",
    name: "FAILure",
    howToGet: "Hold the High Score in SUPERFAIL for 15 Minutes, or get in the Share 11+ times",
    points: 10,
    secret: false,
    image: "placeholder.jpg",
    owned: false,
  },
  {
    id: "trophy_127",
    name: "Fanperson",
    howToGet: "Get a Level 5 Mission Lady Goods",
    points: 10,
    secret: false,
    image: "placeholder.jpg",
    owned: false,
  },
  {
    id: "trophy_128",
    name: "Groovy",
    howToGet: "Received Z-Rewards",
    points: 10,
    secret: false,
    image: "placeholder.jpg",
    owned: false,
  },
  {
    id: "trophy_129",
    name: "Hard of Hearing",
    howToGet: "Win a Mahjong Hand with a Head Bump",
    points: 10,
    secret: false,
    image: "placeholder.jpg",
    owned: false,
  },
  {
    id: "trophy_130",
    name: "It's a Trick",
    howToGet: "Achieved Level 5 in at least one Z-Skill",
    points: 10,
    secret: false,
    image: "placeholder.jpg",
    owned: false,
  },
  {
    id: "trophy_131",
    name: "Jaegermeister",
    howToGet: "Defeated the Titan of the Dark Shift",
    points: 10,
    secret: false,
    image: "placeholder.jpg",
    owned: false,
  },
  {
    id: "trophy_132",
    name: "Let It Ride",
    howToGet: "Bet a Monster Drop on 11 in Roulette - and win",
    points: 10,
    secret: false,
    image: "placeholder.jpg",
    owned: false,
  },
  {
    id: "trophy_133",
    name: "Lightning Brigade",
    howToGet: "Obtain the Special Attack Uniform",
    points: 10,
    secret: false,
    image: "placeholder.jpg",
    owned: false,
  },
  {
    id: "trophy_134",
    name: "Lunatic Drifter",
    howToGet: "Complete a Lunatic Drive",
    points: 10,
    secret: false,
    image: "placeholder.jpg",
    owned: false,
  },
  {
    id: "trophy_135",
    name: "Man Purse",
    howToGet: "Obtain The Tote",
    points: 10,
    secret: false,
    image: "placeholder.jpg",
    owned: false,
  },
  {
    id: "trophy_136",
    name: "Mo' Money",
    howToGet: "Loop with at least 1 Million Ryo",
    points: 10,
    secret: false,
    image: "placeholder.jpg",
    owned: false,
  },
  {
    id: "trophy_137",
    name: "R00t",
    howToGet: "Obtain R00t Rank",
    points: 10,
    secret: false,
    image: "placeholder.jpg",
    owned: false,
  },
  {
    id: "trophy_138",
    name: "Rave Master",
    howToGet: "Win the BillyCon Rave",
    points: 10,
    secret: false,
    image: "placeholder.jpg",
    owned: false,
  },
  {
    id: "trophy_139",
    name: "Rune Encrusted",
    howToGet: "Loop with Boots of Walking, Cowl of the Second HoCage, Dustcloak of Sneaking, Pistol of Repeating, Solid Shades, and Scythe of Razing",
    points: 10,
    secret: false,
    image: "placeholder.jpg",
    owned: false,
  },
  {
    id: "trophy_140",
    name: "Shadowboxing",
    howToGet: "Obtain Shadow Warrior",
    points: 10,
    secret: false,
    image: "placeholder.jpg",
    owned: false,
  },
  {
    id: "trophy_141",
    name: "Shoop The Loop",
    howToGet: "Complete Season 4",
    points: 10,
    secret: false,
    image: "placeholder.jpg",
    owned: false,
  },
  {
    id: "trophy_142",
    name: "Spin to Win",
    howToGet: "Obtain the Lucky Sevens theme",
    points: 10,
    secret: false,
    image: "placeholder.jpg",
    owned: false,
  },
  {
    id: "trophy_143",
    name: "Storm's Sacrifice",
    howToGet: "Obtain the Ninpo Mask via Storm Favor",
    points: 10,
    secret: false,
    image: "placeholder.jpg",
    owned: false,
  },
  {
    id: "trophy_144",
    name: "Summertime",
    howToGet: "Get Five Bright in Flower Wars",
    points: 10,
    secret: false,
    image: "placeholder.jpg",
    owned: false,
  },
  {
    id: "trophy_145",
    name: "Super Arena Wars",
    howToGet: "Loop with the Warrior of Wisdom, Warrior of Courage, and Warrior of Power",
    points: 10,
    secret: false,
    image: "placeholder.jpg",
    owned: false,
  },
  {
    id: "trophy_146",
    name: "The 45ers",
    howToGet: "Help another player get Ultimate Survivor",
    points: 10,
    secret: false,
    image: "placeholder.jpg",
    owned: false,
  },
  {
    id: "trophy_147",
    name: "The First Loser",
    howToGet: "Get the Consolation Prize in The First Loser",
    points: 10,
    secret: false,
    image: "placeholder.jpg",
    owned: false,
  },
  {
    id: "trophy_148",
    name: "The Jaeger",
    howToGet: "Defeat a Titan",
    points: 10,
    secret: false,
    image: "placeholder.jpg",
    owned: false,
  },
  {
    id: "trophy_149",
    name: "The Kunai Stands Alone",
    howToGet: "Loop after Winning the Big Board",
    points: 10,
    secret: false,
    image: "placeholder.jpg",
    owned: false,
  },
  {
    id: "trophy_150",
    name: "The Shoveler",
    howToGet: "Shovel snow with a Megaplow",
    points: 10,
    secret: false,
    image: "placeholder.jpg",
    owned: false,
  },
  {
    id: "trophy_151",
    name: "The White Witch",
    howToGet: "Rescue the White Witch",
    points: 10,
    secret: false,
    image: "placeholder.jpg",
    owned: false,
  },
  {
    id: "trophy_152",
    name: "Threepeat",
    howToGet: "Obtain the Themes You Spin Me Right 'Round, You See Right Through Me, The Flash",
    points: 10,
    secret: false,
    image: "placeholder.jpg",
    owned: false,
  },
  {
    id: "trophy_153",
    name: "Top Billing",
    howToGet: "Land a Role on BillyTV",
    points: 10,
    secret: false,
    image: "placeholder.jpg",
    owned: false,
  },
  {
    id: "trophy_154",
    name: "WonderPets",
    howToGet: "Achieve Level 100 with a Pet",
    points: 10,
    secret: false,
    image: "placeholder.jpg",
    owned: false,
  },
  {
    id: "trophy_155",
    name: "WotAdventure Complete",
    howToGet: "Defeat a WotAdventure",
    points: 10,
    secret: false,
    image: "placeholder.jpg",
    owned: false,
  },
  {
    id: "trophy_156",
    name: "In One Piece",
    howToGet: "Drink Syntherum",
    points: 11,
    secret: false,
    image: "placeholder.jpg",
    owned: false,
  },
  {
    id: "trophy_157",
    name: "28 Dayrolls Later",
    howToGet: "Received the 28 Dayrolls Later Theme",
    points: 20,
    secret: false,
    image: "placeholder.jpg",
    owned: false,
  },
  {
    id: "trophy_158",
    name: "Best In Show",
    howToGet: "Win the BillyCon Cosplay",
    points: 20,
    secret: false,
    image: "placeholder.jpg",
    owned: false,
  },
  {
    id: "trophy_159",
    name: "Do a Barrel Roll",
    howToGet: "Complete Season 9",
    points: 20,
    secret: false,
    image: "placeholder.jpg",
    owned: false,
  },
  {
    id: "trophy_160",
    name: "Feud-Starter",
    howToGet: "Bingo 30 People in one day",
    points: 20,
    secret: false,
    image: "placeholder.jpg",
    owned: false,
  },
  {
    id: "trophy_161",
    name: "Friendly",
    howToGet: "Loop with the Mysterious Power Bloodline",
    points: 20,
    secret: false,
    image: "placeholder.jpg",
    owned: false,
  },
  {
    id: "trophy_162",
    name: "Full of It",
    howToGet: "Loop with Eclipsed",
    points: 20,
    secret: false,
    image: "placeholder.jpg",
    owned: false,
  },
  {
    id: "trophy_163",
    name: "Golden",
    howToGet: "Loop with all nine Golden items",
    points: 20,
    secret: false,
    image: "placeholder.jpg",
    owned: false,
  },
  {
    id: "trophy_164",
    name: "H.A.R.O.",
    howToGet: "Detonate the H.A.R.O.",
    points: 20,
    secret: false,
    image: "placeholder.jpg",
    owned: false,
  },
  {
    id: "trophy_165",
    name: "Open Your Eyes",
    howToGet: "Complete all Vertices of the Eleven-Pronged Seal",
    points: 20,
    secret: false,
    image: "placeholder.jpg",
    owned: false,
  },
  {
    id: "trophy_166",
    name: "Pactmaker",
    howToGet: "Obtain the Calling Theme and the Player Pin",
    points: 20,
    secret: false,
    image: "placeholder.jpg",
    owned: false,
  },
  {
    id: "trophy_167",
    name: "Stand Tall",
    howToGet: "Acquire The Touch",
    points: 20,
    secret: false,
    image: "placeholder.jpg",
    owned: false,
  },
  {
    id: "trophy_168",
    name: "Stormy",
    howToGet: "Loop with Storm's Fury, Storm's Embrace, and Storm's Path",
    points: 20,
    secret: false,
    image: "placeholder.jpg",
    owned: false,
  },
  {
    id: "trophy_169",
    name: "The Beast",
    howToGet: "Win the BillyCon Video Game Tournament",
    points: 20,
    secret: false,
    image: "placeholder.jpg",
    owned: false,
  },
  {
    id: "trophy_170",
    name: "The Long Dream",
    howToGet: "Defeat FutureMiku, the final boss of Billy Idol",
    points: 20,
    secret: false,
    image: "placeholder.jpg",
    owned: false,
  },
  {
    id: "trophy_171",
    name: "The Last Dragon",
    howToGet: "Loop with The Glow",
    points: 20,
    secret: false,
    image: "placeholder.jpg",
    owned: false,
  },
  {
    id: "trophy_172",
    name: "Ultimate Survivor",
    howToGet: "Defeat The Bawg",
    points: 20,
    secret: false,
    image: "placeholder.jpg",
    owned: false,
  },
  {
    id: "trophy_173",
    name: "Gallery II",
    howToGet: "Complete the second Snooty Gallery Artwork",
    points: 20,
    secret: true,
    image: "placeholder.jpg",
    owned: false,
  },
  {
    id: "trophy_174",
    name: "If I Could Turn Back Time",
    howToGet: "Get the Pocketwatch working again",
    points: 20,
    secret: true,
    image: "placeholder.jpg",
    owned: false,
  },
  {
    id: "trophy_175",
    name: "Okkusenman",
    howToGet: "Achieve a Rank of S against a WorldKaiju",
    points: 20,
    secret: true,
    image: "placeholder.jpg",
    owned: false,
  },
  {
    id: "trophy_176",
    name: "One Twenty One",
    howToGet: "Level A Leven to 11",
    points: 20,
    secret: true,
    image: "placeholder.jpg",
    owned: false,
  },
  {
    id: "trophy_177",
    name: "Pierce the Heavens",
    howToGet: "Arrive in the AboveGround",
    points: 20,
    secret: true,
    image: "placeholder.jpg",
    owned: false,
  },
  {
    id: "trophy_178",
    name: "Rising Sun",
    howToGet: "Defeat Triple H Lvl. 2 in a Mahjong Match",
    points: 20,
    secret: true,
    image: "placeholder.jpg",
    owned: false,
  },
  {
    id: "trophy_179",
    name: "Scrapbook Hero",
    howToGet: "Collect all six Bromides from Candyween",
    points: 20,
    secret: true,
    image: "placeholder.jpg",
    owned: false,
  },
  {
    id: "trophy_180",
    name: "TACOCAT",
    howToGet: "Beat the final character battle in Flower Wars",
    points: 20,
    secret: true,
    image: "placeholder.jpg",
    owned: false,
  },
  {
    id: "trophy_181",
    name: "The Festival",
    howToGet: "Defeated the Eleven Tails at The Festival",
    points: 20,
    secret: true,
    image: "placeholder.jpg",
    owned: false,
  },
  {
    id: "trophy_182",
    name: "The Sky Will Strike",
    howToGet: "Achieve Protagonist Rank",
    points: 20,
    secret: true,
    image: "placeholder.jpg",
    owned: false,
  },
  {
    id: "trophy_183",
    name: "Tiny Three",
    howToGet: "Bank 3+ different Tiny Bee Weapons",
    points: 20,
    secret: true,
    image: "placeholder.jpg",
    owned: false,
  },
  {
    id: "trophy_184",
    name: "Eleven Tails",
    howToGet: "Drain The Eleven-Tailed Fox",
    points: 20,
    secret: false,
    image: "placeholder.jpg",
    owned: false,
  },
  {
    id: "trophy_185",
    name: "The Cursed Wave",
    howToGet: "Loop with all eight Lost Weapons",
    points: 40,
    secret: false,
    image: "placeholder.jpg",
    owned: false,
  },
  {
    id: "trophy_186",
    name: "Choosing Sides",
    howToGet: "Gain the Fate or Destiny Bloodline",
    points: 60,
    secret: false,
    image: "placeholder.jpg",
    owned: false,
  },
];
